name: New release created
# This workflow is triggered on pushes to the repository.
on:
  release:
    types:
      - created

jobs:
  build:
    # Job name is Greeting
    name: echo release
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Echo release naùe
        run: echo 'The time was ${{ github.event.release.tag_name }}. ${{github.event.release.tarball_url}}'
